dist: xenial
language: minimal
sudo: required
addons:
  apt:
    packages:
    - p7zip-full
    - mtools
    - jq
    - u-boot-tools
    - html-xml-utils
    - qemu-user-static
    - binfmt-support
    - squashfs-tools
    - bsdtar
    - axel
script:
- make build_armbian=y build
- ls -l output
deploy:
  provider: releases
  api_key:
    secure: NTzfr/4TtlMwnpgwXLin1f7BQ+/a+6WJ3eibAUSOnA7xyxXweweGFHFI7Y11QMj6W8ETIvgVDdPUQ+dp2wXtHzG5wtS5wNprv+pnmjKWageIVWn8fTJx/MIgdfneQeid8Bi7yb68x7polh+hRN0SQd4/YPFdFi2VXyHnlTdqBJoYbvxkz08nNxaI0XDiKrAlDUSPEuT7OvImEXFGvk58FS+/XmFRmdNDPslcjGQ+ap0yA2ufxUZlM2FBs/DqwvIXAIxUDQHtYejHlpGr1BJAwNq522c/GJb8LQqT07FMADaSV14mzbBSj2RrU0PiwnKn/EZIk32o/40twjHI2wp1yxbd5cXDJvKmTHzirMSsOxZnEtxUmwGh0Yg9rNF8EAJLDuD0EFmaL5LOWlf6R/7IkJ31pN4Dgd904BtzZXgLzFtTawv6SeN3YsDIk+NWllCAeN6YEK5upWPzyTnxnuaERpMRbqp5pF276Ke7zZ/OvEo41J9f6BlUy7YIdKSEgucyPF8qgtVJ4GmINAKrm4TnDdwvlSloERGpR0Nbgt+Nhho7c+2BbOYkedYOAUZCd348/YgXObeolcarg323HuP7+NtkHOM2YmdJ4+qG1H3Jug/FfN77PMECwH9JqjmrxJuM8OLkeiwzRrAVv4OdSAbsvbqj5cT4LdSy/iiWwDB5Pls=
  file: output/*.xz
  skip_cleanup: true
  overwrite: true
  file_glob: true
  on:
    repo: xiangtailiang/build-beikeyun
    tags: true
